// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	reports "infion-BE/businesses/reports"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, reportsDomain
func (_m *Repository) Delete(ctx context.Context, reportsDomain *reports.Domain) (reports.Domain, error) {
	ret := _m.Called(ctx, reportsDomain)

	var r0 reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reports.Domain) reports.Domain); ok {
		r0 = rf(ctx, reportsDomain)
	} else {
		r0 = ret.Get(0).(reports.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reports.Domain) error); ok {
		r1 = rf(ctx, reportsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, reportsId
func (_m *Repository) GetByID(ctx context.Context, reportsId int) (reports.Domain, error) {
	ret := _m.Called(ctx, reportsId)

	var r0 reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) reports.Domain); ok {
		r0 = rf(ctx, reportsId)
	} else {
		r0 = ret.Get(0).(reports.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, reportsId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReports provides a mock function with given fields: ctx
func (_m *Repository) GetReports(ctx context.Context) ([]reports.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []reports.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reports.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportsByThreadID provides a mock function with given fields: ctx, threadID
func (_m *Repository) GetReportsByThreadID(ctx context.Context, threadID int) ([]reports.Domain, error) {
	ret := _m.Called(ctx, threadID)

	var r0 []reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reports.Domain); ok {
		r0 = rf(ctx, threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reports.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportsByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) GetReportsByUserID(ctx context.Context, userID int) ([]reports.Domain, error) {
	ret := _m.Called(ctx, userID)

	var r0 []reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reports.Domain); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reports.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, reportsDomain
func (_m *Repository) Store(ctx context.Context, reportsDomain *reports.Domain) (reports.Domain, error) {
	ret := _m.Called(ctx, reportsDomain)

	var r0 reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reports.Domain) reports.Domain); ok {
		r0 = rf(ctx, reportsDomain)
	} else {
		r0 = ret.Get(0).(reports.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reports.Domain) error); ok {
		r1 = rf(ctx, reportsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, reportsDomain
func (_m *Repository) Update(ctx context.Context, reportsDomain *reports.Domain) (reports.Domain, error) {
	ret := _m.Called(ctx, reportsDomain)

	var r0 reports.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reports.Domain) reports.Domain); ok {
		r0 = rf(ctx, reportsDomain)
	} else {
		r0 = ret.Get(0).(reports.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reports.Domain) error); ok {
		r1 = rf(ctx, reportsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
