version: "3"

services:
    infion-be:
        build: .
        restart: "no"
        ports:
            - 8080:8080

    mysql-infion-be:
        image: mariadb:10.1
        hostname: mysql.docker
        command: --init-file /app/app/config/init.sql
        volumes:
            - ./init.sql:/app/app/config/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_DATABASE: infion
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3336:3306
        restart: "no"
