// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	likeThreads "infion-BE/businesses/likeThreads"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, likeThreadsDomain
func (_m *Repository) Delete(ctx context.Context, likeThreadsDomain *likeThreads.Domain) (likeThreads.Domain, error) {
	ret := _m.Called(ctx, likeThreadsDomain)

	var r0 likeThreads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *likeThreads.Domain) likeThreads.Domain); ok {
		r0 = rf(ctx, likeThreadsDomain)
	} else {
		r0 = ret.Get(0).(likeThreads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *likeThreads.Domain) error); ok {
		r1 = rf(ctx, likeThreadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, likeThreadsId
func (_m *Repository) GetByID(ctx context.Context, likeThreadsId int) (likeThreads.Domain, error) {
	ret := _m.Called(ctx, likeThreadsId)

	var r0 likeThreads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) likeThreads.Domain); ok {
		r0 = rf(ctx, likeThreadsId)
	} else {
		r0 = ret.Get(0).(likeThreads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, likeThreadsId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, likeThreadsDomain
func (_m *Repository) Store(ctx context.Context, likeThreadsDomain *likeThreads.Domain) (likeThreads.Domain, error) {
	ret := _m.Called(ctx, likeThreadsDomain)

	var r0 likeThreads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *likeThreads.Domain) likeThreads.Domain); ok {
		r0 = rf(ctx, likeThreadsDomain)
	} else {
		r0 = ret.Get(0).(likeThreads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *likeThreads.Domain) error); ok {
		r1 = rf(ctx, likeThreadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, likeThreadsDomain
func (_m *Repository) Update(ctx context.Context, likeThreadsDomain *likeThreads.Domain) (likeThreads.Domain, error) {
	ret := _m.Called(ctx, likeThreadsDomain)

	var r0 likeThreads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *likeThreads.Domain) likeThreads.Domain); ok {
		r0 = rf(ctx, likeThreadsDomain)
	} else {
		r0 = ret.Get(0).(likeThreads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *likeThreads.Domain) error); ok {
		r1 = rf(ctx, likeThreadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
