// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	roles "infion-BE/businesses/roles"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, rolesDomain
func (_m *Repository) Delete(ctx context.Context, rolesDomain *roles.Domain) (roles.Domain, error) {
	ret := _m.Called(ctx, rolesDomain)

	var r0 roles.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *roles.Domain) roles.Domain); ok {
		r0 = rf(ctx, rolesDomain)
	} else {
		r0 = ret.Get(0).(roles.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *roles.Domain) error); ok {
		r1 = rf(ctx, rolesDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, rolesId
func (_m *Repository) GetByID(ctx context.Context, rolesId int) (roles.Domain, error) {
	ret := _m.Called(ctx, rolesId)

	var r0 roles.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) roles.Domain); ok {
		r0 = rf(ctx, rolesId)
	} else {
		r0 = ret.Get(0).(roles.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, rolesId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, rolesDomain
func (_m *Repository) Store(ctx context.Context, rolesDomain *roles.Domain) (roles.Domain, error) {
	ret := _m.Called(ctx, rolesDomain)

	var r0 roles.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *roles.Domain) roles.Domain); ok {
		r0 = rf(ctx, rolesDomain)
	} else {
		r0 = ret.Get(0).(roles.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *roles.Domain) error); ok {
		r1 = rf(ctx, rolesDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, rolesDomain
func (_m *Repository) Update(ctx context.Context, rolesDomain *roles.Domain) (roles.Domain, error) {
	ret := _m.Called(ctx, rolesDomain)

	var r0 roles.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *roles.Domain) roles.Domain); ok {
		r0 = rf(ctx, rolesDomain)
	} else {
		r0 = ret.Get(0).(roles.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *roles.Domain) error); ok {
		r1 = rf(ctx, rolesDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
