// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	threads "infion-BE/businesses/threads"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, threadsDomain
func (_m *Repository) Delete(ctx context.Context, threadsDomain *threads.Domain) (threads.Domain, error) {
	ret := _m.Called(ctx, threadsDomain)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *threads.Domain) threads.Domain); ok {
		r0 = rf(ctx, threadsDomain)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *threads.Domain) error); ok {
		r1 = rf(ctx, threadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, threadsId
func (_m *Repository) GetByID(ctx context.Context, threadsId int) (threads.Domain, error) {
	ret := _m.Called(ctx, threadsId)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) threads.Domain); ok {
		r0 = rf(ctx, threadsId)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, threadsId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetThreads provides a mock function with given fields: ctx
func (_m *Repository) GetThreads(ctx context.Context) ([]threads.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []threads.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]threads.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetThreadsByCategory provides a mock function with given fields: ctx, category
func (_m *Repository) GetThreadsByCategory(ctx context.Context, category string) ([]threads.Domain, error) {
	ret := _m.Called(ctx, category)

	var r0 []threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []threads.Domain); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]threads.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, threadsDomain
func (_m *Repository) Store(ctx context.Context, threadsDomain *threads.Domain) (threads.Domain, error) {
	ret := _m.Called(ctx, threadsDomain)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *threads.Domain) threads.Domain); ok {
		r0 = rf(ctx, threadsDomain)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *threads.Domain) error); ok {
		r1 = rf(ctx, threadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, threadsDomain
func (_m *Repository) Update(ctx context.Context, threadsDomain *threads.Domain) (threads.Domain, error) {
	ret := _m.Called(ctx, threadsDomain)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *threads.Domain) threads.Domain); ok {
		r0 = rf(ctx, threadsDomain)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *threads.Domain) error); ok {
		r1 = rf(ctx, threadsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
